# Generated by Django 2.1.4 on 2018-12-26 23:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='transaction/%Y/%m/%d/', verbose_name='File')),
                ('file_hash', models.CharField(editable=False, max_length=32)),
                ('stellar_response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Stellar transaction response data')),
                ('is_submitted', models.BooleanField(default=False)),
                ('stellar_transaction_link', models.URLField(null=True)),
                ('stellar_transaction_hash', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-created',),
            },
        ),
    ]
